package com.banvenez.ast.dto.Suscripcion;

import lombok.Data;

@Data

public class data {

    private String  codigo_localidad;
    private String  plan;
    private String  fecha_inicio;
    private Integer  codigo_prima;
    private Integer  codigo;
    private Integer  certificado;
    private String  nombre;
    private String  fecha_ingreso;
    private String fecha_nacimiento;
    private String sexo;
    private String estado_civil;
    private String parentesco;
    private String  status;
    private String fecha_registro;
    private String plazos_espera;
    private String poliza_exceso;
    private String  codigo_filial;
    private Integer  cedula;
    private String fecha_egreso;
    private String codigo_empleado;
    private String aseguradora_exceso;
    private String numero_poliza_exceso;
    private String tipo_de_empleado;
    private String hecho_por;
    private String observaciones;
    private String plan_exceso;
    private String fecha_inicio_exceso;
    private Double codigo_prima_exceso;
    private Double sueldo;
    private String plazos_de_espera_ezceso;
    private String observaciones_exceso;
    private String revisar_basico;
    private String revisar_exceso;
    private String fecha_ingreso_exceso;
    private String fecha_egreso_exceso;
    private Double prorrata;
    private String cmf;
    private String rl;
    private String direccion;
    private String maternidad;
    private String exclusion_enfermedades;
    private String sts_procesado;
    private String cuenta_bancaria;
    private Double cup;
    private String sts_procesado_exc;
    private String centro_costo;
    private String sts_procesado_egreso;
    private String sts_procesado_egreso_exc;
    private String numero_poliza;
    private String odontologico;
    private String modificado_por;
    private String fecha_modificacion;
    private String maquina;
    private String fecha_modif;
    private String ficha;
    private String congenita;
    private String pre_existente;
    private Integer codigo_odontologico;
    private String ambulancia;
    private Integer codigo_ambulancia;
    private String asistencia;
    private Integer codigo_asistencia;
    private String bono_plan_incentivo;
    private String aut_ren;
    private Integer descuento;
    private String anexo_vida;
    private Integer codigo_anexo_vida;
    private String renovar;
    private String usuario_renovacion;
    private String observaciones_renovacion;
    private String email;
    private Integer id_masivo;
    private String mat_exceso;
    private String enfermedad_cronica;
    private String modulo_cronico;
    private String mat_exceso2;
    private String codigo_medico_mil_razones;
    private Double suma_maternidad;
    private String nacionalidad;
    private String cod_area;
    private String celular;
    private String f_ing_mat_exc;
    private Double suma_maternidad_exc;
    private String codigo_exclusion;
    private String fecha_solicitud_ingreso;
    private String fecha_solicitud_egreso;

}
